name: Populate Database

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

env:
  DJANGO_SETTINGS_MODULE: project.settings

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Print DB host for verification
        run: |
          python -c "import django; django.setup(); from django.conf import settings; print('🔎 DB HOST =', settings.DATABASES['default']['HOST'])"


      - name: Set up Django (env vars, DB, etc.)
        run: |
          python manage.py makemigrations 
          python manage.py migrate

      - name: Populate db
        run: |
          python manage.py populate_db
